### ISSUE TITLE
Throw error A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by futurist** [freeman-lab/pdf-to-png#5]
When exec below command using cli:

```
pdf-to-png -i print.pdf -o output.png
```

Throw error

**A JavaScript error occurred in the main process**

```
Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/pdf-to-png/node_modules/_electron-spawn@4.1.1@electron-spawn/cli.js:4:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/pdf-to-png/node_modules/_electron-spawn@4.1.1@electron-spawn/cli.js:31:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

Using macOS 10.12.3, and `npm i -g pdf-to-png`

[print.pdf](https://github.com/freeman-lab/pdf-to-png/files/1176296/print.pdf)

PDF is attached

**Comment by geyang** [comment]
same problem here!

**Comment by geyang** [comment]
@freeman-lab Jeremy any thoughts on this? I can take a look but it will take a while.
